sudo: false

language: python
python:
  - "3.4"

addons:
  apt:
    packages:
      - oracle-java8-installer

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements/all-sources.txt"
  - "pip install python-coveralls"
  - "pip install ."

# command to run tests
script: 
  - "make test"

after_success:
  coveralls

# whitelist
branches:
  only:
    - master