sudo: false

language: python
python:
  - "3.4"

addons:
  apt:
    packages:
      - oracle-java8-installer

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements/all-sources.txt"
  - "pip install python-coveralls"
  - "pip install ."
  
before_script:
  - "git clone https://github.com/owlcollab/owltools.git"
  - "cd owltools/OWLTools-Parent/"
  - "mvn clean package -DskipTests=true"
  - "cd ../.."

# command to run tests
script: 
  - "export PATH=$PATH:/home/travis/build/monarch-initiative/dipper/owltools/OWLTools-Runner/bin/"
  - "make test"

after_success:
  coveralls

# whitelist
branches:
  only:
    - master
    - variable_imports
